services:
  fastapi:
    build: .
    container_name: university_app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env.docker
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: ["fastapi", "run", "main.py", "--port", "8000"]

  faststream:
    container_name: university_worker
    build: .
    env_file:
      - .env.docker
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: ["faststream", "run", "subscriptions.app:app"]

  postgres:
    image: postgres:latest
    container_name: university_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d habr"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  maildev:
    image: maildev/maildev
    container_name: university_mail
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  redis:
    image: redis:latest
    container_name: university_redis
    ports:
      - "6378:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  pgdata:
    driver: local
  rabbitmq-data:
